### ISSUE TITLE
Comments inside selectors don't get parsed

### ISSUE THREAD

**Issue by bergie** [Hydrotoast/vim-gss#1]
Example:

```
// This comment works
#container {
  width == ::window[width] !require;

  // This comment doesn't
  height == 100 !strong;
}
// This comment works again
```

Looks like:

![screenshot 2015-02-25 at 15 17 30](https://cloud.githubusercontent.com/assets/3346/6372056/765f637c-bd01-11e4-9a8e-6ce4e1ee020c.png)

**Comment by Hydrotoast** [comment]
Thanks @bergie. I added this to my test cases and I'll push changes later tonight.
